config/routes.rb
Checklist::Application.routes.draw do
  get "splash/home"

  devise_for :users

  resources :children

  resources :tasks
  root to: 'tasks#index'
end

app/models/child.rb
class Child < ActiveRecord::Base
  attr_accessible :date_of_birth, :image, :name, :total_points
  mount_uploader :image, ImageUploader
  
  has_many :tasks
  
end

app/models/task.rb
class Task < ActiveRecord::Base
  attr_accessible :complete, :name, :points, :due_date
  
  belongs_to :child
 
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/children_controller.rb
class ChildrenController < ApplicationController
  
  before_filter :authenticate_user!
  # GET /children
  # GET /children.json
  def index
    @children = Child.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @children }
    end
  end

  # GET /children/1
  # GET /children/1.json
  def show
    @child = Child.find(params[:id])
  
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @child }
    end
  end

  # GET /children/new
  # GET /children/new.json
  def new
    @child = Child.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @child }
    end
  end

  # GET /children/1/edit
  def edit
    @child = Child.find(params[:id])
  end

  # POST /children
  # POST /children.json
  def create
    @child = Child.new(params[:child])

    respond_to do |format|
      if @child.save
        format.html { redirect_to @child, notice: 'Child was successfully created.' }
        format.json { render json: @child, status: :created, location: @child }
      else
        format.html { render action: "new" }
        format.json { render json: @child.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /children/1
  # PUT /children/1.json
  def update
    @child = Child.find(params[:id])

    respond_to do |format|
      if @child.update_attributes(params[:child])
        format.html { redirect_to @child, notice: 'Child was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @child.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /children/1
  # DELETE /children/1.json
  def destroy
    @child = Child.find(params[:id])
    @child.destroy

    respond_to do |format|
      format.html { redirect_to children_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/splash_controller.rb
class SplashController < ApplicationController
  
  def home
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  
  before_filter :authenticate_user!
  
  
  def index
    @incomplete_tasks = Task.where(complete: false).order(:due_date)
    @complete_tasks = Task.where(complete: true)
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.create!(params[:task])
    redirect_to tasks_url
  end

  def update
    @task = Task.find(params[:id])
    @task.update_attributes!(params[:task])
    redirect_to tasks_url
  end

  def destroy
    @task = Task.destroy(params[:id])
    redirect_to tasks_url
  end
  
  
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/children_helper.rb
module ChildrenHelper
end

app/helpers/splash_helper.rb
module SplashHelper
end

app/helpers/tasks_helper.rb
module TasksHelper

end

app/views/children/_form.html.erb
<%= form_for(@child) do |f| %>
  <% if @child.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@child.errors.count, "error") %> prohibited this child from being saved:</h2>

      <ul>
      <% @child.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :image %><br />
    <%= f.file_field :image %>
  </div>

  <div class="field">
    <%= f.label :date_of_birth %><br />
    <%= f.text_field:date_of_birth %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/children/edit.html.erb
<h1>Editing child</h1>

<%= render 'form' %>

<%= link_to 'Show', @child %> |
<%= link_to 'Back', children_path %>

app/views/children/index.html.erb
<h1>Children</h1>



<% @children.each do |child| %>

    
   <div class="well"> <%= image_tag child.image_url(:thumb) %>
    <%= child.name %>
    <%= child.total_points %>
    <%= child.date_of_birth %>
    <%= link_to 'Show', child %>
    <%= link_to 'Edit', edit_child_path(child) %>
    <%= link_to 'Destroy', child, method: :delete, data: { confirm: 'Are you sure?' } %>
</div>
<% end %>


<br />

<div class="well"><%= link_to 'Add Child', new_child_path %></div>

app/views/children/new.html.erb
<h1>New child</h1>

<%= render 'form' %>

<%= link_to 'Back', children_path %>

app/views/children/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @child.name %>
</p>

<p>
  <b>Image:</b>
  <%= image_tag @child.image_url(:thumb) %>
</p>

<p>
  <b>Total points:</b>
  <%= @child.total_points %>
</p>

<p>
  <b>Date of birth:</b>
  <%= @child.date_of_birth %>
</p>


<%= link_to 'Edit', edit_child_path(@child) %> |
<%= link_to 'Back', children_path %>

app/views/layouts/_cnav.html.erb
<div class="center-nav"></div>
	<ul>
		<li><%= link_to "Chore", "#" %></li>
		<li><%= link_to "Rewards", "#" %></li>
		<li><%= link_to "Children", "#" %></li>
	</ul>
</div>

app/views/layouts/_navbar.html.erb
<div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
  		<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        	</a>
        	<a class="brand scroller" data-section="body" href="index.html">
              <%= image_tag 'Book-48.png' %>Chorebook
          </a>
	  	  <div class="nav-collapse collapse">
              <ul class="nav pull-right">
	              <% if user_signed_in? %>
								  <strong><%= link_to current_user.email, edit_user_registration_path   %></strong> |
								  <%= link_to "Logout", destroy_user_session_path, method: :delete %>
								<% else %>

								  <li><a href="#" class="scroller" data-section="#features">Features</a></li>
								  <li><a href="#" class="scroller" data-section="#pricing">About</a></li>
								  <li><a href="#" class="scroller" data-section="footer">Contact us</a></li>

								  <li><%= link_to 'Sign Up', new_user_registration_path, class: "btn-header	" %></li> 
								  <li><%= link_to 'Sign In', new_user_session_path, class: "btn-header" %></li>
								<% end %>
                  
              </ul>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chorebook</title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tag %>
  </head>
  <body>
   

<%= render 'layouts/navbar' %>
		
<div class="container">
	 
		<div class="topshit">
			<div class="centre-nav">	
			
				<div class="download_btn"><%= image_tag 'web-buttons.png' %></div>
				<div class="download_btn"><%= image_tag 'web-buttons.png' %></div>
				<div class="download_btn"><%= image_tag 'web-buttons.png' %></div>
			
			</div>
						
					
			
		
    </div>
    <div class="bottomshit">
    	<%= yield %> 
    </div>   
   
    
</div>	
     
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for @task do |f| %>
  <%= f.text_field :name, placeholder: 'Describe chore' %>
  <%= f.number_field :points, placeholder: 'points' %>
  <%= f.text_field :due_date, placeholder: 'Due date' %>
  <%= f.submit %>
<% end %>

app/views/tasks/_task.html.erb
<%= form_for task do |f| %>
  <%= f.check_box :complete %>
  <%= f.submit "Update" %>
  <%= f.label :complete, task.points %> pts,
   Jonjo
  <%= f.label :complete, task.name %>,
  
  
  <%= f.label :complete, task.due_date.strftime("due: %A")  %>
  <span class="admin"><%= link_to (image_tag "1354332059_delete.png"), task, method: :delete, data: {confirm: "Are you sure?"} %>
<%= link_to time_ago_in_words(task.created_at) + " ago", task %></span>

<% end %>

app/views/tasks/index.html.erb
<h1>Check List</h1>

<%= link_to "+ Chore", new_task_path, id: "new_link" %>


<div class="tasks" id="incomplete_tasks">
  <%= render @incomplete_tasks %>
</div>


<div class="tasks" id="complete_tasks">
  <%= render @complete_tasks %>
</div>

app/views/tasks/new.html.erb
<h1>New Chore</h1>

<%= render 'form' %>

<p><%= link_to "Back to tasks", tasks_path %></p>